import Image from 'next/image';
import Link from 'next/link';
import { assetPath } from '@/lib/paths';
import type { ContentPage } from '@/lib/types';
import { beliefs, church, forms, groupFaqs, leaders, neighborhoodGroups } from '@/content/site';
import { ManagedForm } from './ManagedForm';
import { InteractiveCalendar } from './InteractiveCalendar';

function AboutContent() {
  return <>
    <section className="content-section split-section">
      <div><p className="eyebrow">Our Gatherings</p><h2>Worship Gathering</h2><p>Every Sunday at 10:30am, we gather at 11300 Old San Antonio Rd. to celebrate what God has done for us in the Gospel of Jesus and what God is doing through us as a body of believers. Everyone is welcome.</p><p>We worship through singing, the study of the Bible and preaching, communion, testimonies of God’s faithfulness, baptism, and prayer.</p></div>
      <div><p className="eyebrow">Life together</p><h2>Neighborhood Groups</h2><p>A Neighborhood Group is a family of Jesus followers living together on God’s mission. It is a smaller expression of the church—ordinary people growing as disciples while making disciples in everyday life.</p><p>Our groups meet at various times and places throughout the week.</p></div>
    </section>
    <section className="content-section tone-section"><p className="eyebrow">Our Identity</p><h2>Family. Disciples. Mission.</h2><div className="three-column"><p><strong>Family</strong><br />As children of God, we provide care and encouragement for one another. <em>Ephesians 2:19–22</em></p><p><strong>Disciples</strong><br />We are Jesus-followers growing in the good news that God loves us, Jesus saves us, and the Spirit empowers us. <em>2 Corinthians 5:17–21</em></p><p><strong>Mission</strong><br />We all have a purpose to make more disciples by pointing others to Jesus. <em>Matthew 28:18–20</em></p></div></section>
    <section className="content-section prose"><p className="eyebrow">More than a building</p><h2>What is the Church anyway?</h2><p>The Bible uses the word “church” to describe people connected to one another because of Jesus. While we have a building and gatherings, the church is not defined by a building we enter or an event we attend. We, the people, are the church.</p><p>God rescued his people through Jesus and calls the church to be his family living on his mission together. Joyfully living out the New Testament’s “one another” commands in light of the gospel is what we mean by being the church together.</p></section>
  </>;
}

export function PageContent({ page }: { page: ContentPage }) {
  switch (page.kind) {
    case 'about': return <AboutContent />;
    case 'beliefs': return <><section className="content-section"><p className="eyebrow">Core Beliefs</p><div className="belief-list">{beliefs.map(([title, copy, references], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{title}</h2><p>{copy}</p><small>{references}</small></div></article>)}</div></section><ManagedForm form={forms.beliefs} /></>;
    case 'leadership': return <><section className="content-section"><div className="people-grid">{leaders.map(([name, role, image]) => <article className="person-card" key={name}>{image ? <Image src={assetPath(image)} alt={name} width={500} height={625} /> : <div className="person-placeholder" aria-hidden="true">P</div>}<h2>{name}</h2><p>{role}</p></article>)}</div></section><section className="content-section split-section tone-section"><div><p className="eyebrow">Leadership</p><h2>Structure</h2><p>Jesus Christ is the head of the Church. At each local expression, he calls specific followers to provide leadership and care. Their primary role is to equip the church to be the church, not to take on the entire ministry of the congregation themselves.</p></div><div><p className="eyebrow">Elders</p><h2>Shared leadership</h2><p>Elders are biblically qualified men who govern and teach sound doctrine. Point Community’s Elder Team leads together—equal in authority and accountability, unique in function, and unified in direction and vision.</p></div></section><section className="content-section prose"><p className="eyebrow">Partnerships</p><h2>Serving Austin together</h2><p>The local church was not created to operate in isolation. Our strongest partnership is the Association of Hill Country Churches, committed to reaching every person in Greater Austin with the life-changing reality of Jesus.</p><p>Other partners include Christ Together Austin, Austin Church Planting Network, Austin Disaster Relief Network, TruCare Pregnancy Center, South Austin Young Life, Austin Bridge Builders Alliance, and Akins High School.</p></section></>;
    case 'kids': return <><section className="content-section split-section image-split"><div><Image src={assetPath('/assets/pages/kids-ministry-2.jpeg')} alt="Point ATX kids ministry" width={500} height={624} /></div><div><p className="eyebrow">First Point</p><h2>Next Generation<br />Kids Ministry</h2><p>First Point is our ministry for our youngest children. The goal is to point children from birth through preschool toward the amazing love of God. Our volunteers love and serve these little lives week in and week out using the First Look curriculum.</p><p>Children are always welcome in the main gathering. If you need to step out with an infant, audio of the message is available in the lobby.</p><p><small>All volunteers are required to pass a background check before working in kids ministry.</small></p><div className="service-callout"><strong>Sunday Morning Child Care</strong><span>10:30am</span></div></div></section><section className="content-section wide-photo"><Image src={assetPath('/assets/pages/kids-ministry-3.jpeg')} alt="Children and families at Point ATX" width={1000} height={668} /></section><ManagedForm form={forms.kids} /></>;
    case 'calendar': return <><section className="content-section"><InteractiveCalendar /></section><ManagedForm form={forms.calendar} /></>;
    case 'groups': return <><section className="content-section group-grid">{neighborhoodGroups.map(([name, time, address, leader]) => <article key={name}><h2>{name}</h2><p className="group-time">{time}</p><p>{address}</p><p><strong>Leaders:</strong> {leader}</p></article>)}</section><ManagedForm form={forms.groups} /><section className="content-section faq-section"><p className="eyebrow">Common questions</p><h2>Finding your group</h2>{groupFaqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section></>;
    case 'giving': return <><section className="content-section prose"><p className="eyebrow">Why we give</p><h2>Generosity is worship</h2><p>What we do with what God has given us shows the world where our hearts are and helps proclaim the gospel. We want to glorify God with every area of our lives, including our finances.</p></section><section className="content-section giving-options"><article><span>01</span><h2>Give Online</h2><p>Give a one-time donation or set up a recurring gift securely through our current giving partner.</p><a className="button button--dark" href={church.givingUrl} target="_blank" rel="noreferrer">Open secure giving</a></article><article><span>02</span><h2>Give In Person</h2><p>A giving box is available in the back of the sanctuary for cash and check donations.</p></article></section><ManagedForm form={forms.giving} /></>;
    case 'contact': return <><section className="content-section contact-grid"><div><p className="eyebrow">Office Hours</p><h2>Monday–Friday<br />9am–5pm</h2><p><a href={`mailto:${church.email}`}>{church.email}</a></p><p>{church.address}</p><a className="text-link" href="https://maps.google.com/?q=11300+Old+San+Antonio+Rd+Manchaca+TX+78652" target="_blank" rel="noreferrer">Get directions →</a></div><ManagedForm form={forms.contact} /></section><section className="content-section rental-link"><div><p className="eyebrow">Need a space?</p><h2>Building Rental</h2></div><Link className="button" href="/building-rental">Request the building</Link></section></>;
    case 'form': return <section className="content-section standalone-form"><ManagedForm form={forms[page.slug]} /></section>;
  }
}
