name: Publish Staging candidate
run-name: Publish Staging candidate ${{ github.event.client_payload.jobId }}
on:
  repository_dispatch:
    types: [publish-candidate]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  publish:
    if: github.ref == 'refs/heads/main' && ((github.repository == 'PointCommunity/pointsite-staging' && github.event.client_payload.builderOrigin == 'https://builder.eaglepass.io') || (github.repository == 'PointCommunity/pointsite-staging-canary' && github.event.client_payload.builderOrigin == 'https://builder-canary.eaglepass.io'))
    uses: PointCommunity/pointsite-staging/.github/workflows/publish-runtime.yml@3789751c8725f023945b9348d7b3b43737976f81
    with:
      builder_origin: ${{ github.event.client_payload.builderOrigin }}
      job_id: ${{ github.event.client_payload.jobId }}
      nonce: ${{ github.event.client_payload.nonce }}
      target: staging
